"""add trip fields to tourist locations

Revision ID: c725d4d68bf5
Revises: 1ad58a14f0a2
Create Date: 2026-09-11 07:40:29.181828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c725d4d68bf5'
down_revision: Union[str, Sequence[str], None] = '1ad58a14f0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourist_locations', sa.Column('trip_id', sa.Integer(), nullable=False))
    op.add_column('tourist_locations', sa.Column('speed', sa.Double(), nullable=True))
    op.add_column('tourist_locations', sa.Column('heading', sa.Double(), nullable=True))
    op.alter_column('tourist_locations', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tourist_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tourist_locations_recorded_at'), 'tourist_locations', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_tourist_locations_tourist_id'), 'tourist_locations', ['tourist_id'], unique=False)
    op.create_index(op.f('ix_tourist_locations_trip_id'), 'tourist_locations', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'tourist_locations', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tourist_locations', type_='foreignkey')
    op.drop_index(op.f('ix_tourist_locations_trip_id'), table_name='tourist_locations')
    op.drop_index(op.f('ix_tourist_locations_tourist_id'), table_name='tourist_locations')
    op.drop_index(op.f('ix_tourist_locations_recorded_at'), table_name='tourist_locations')
    op.alter_column('tourist_locations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tourist_locations', 'recorded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tourist_locations', 'heading')
    op.drop_column('tourist_locations', 'speed')
    op.drop_column('tourist_locations', 'trip_id')
    # ### end Alembic commands ###
