"""add geofence relationship to alerts

Revision ID: d855c46111a6
Revises: 0e425062c260
Create Date: 2026-08-18 19:41:10.021698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd855c46111a6'
down_revision: Union[str, Sequence[str], None] = '0e425062c260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('geofence_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'geofence_zones', ['geofence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'geofence_id')
    # ### end Alembic commands ###
